package criticfi_mydatos;
// Generated May 21, 2016 10:26:57 AM by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Integer idAuthor;
     private String nameLast;
     private String nameFirst;
     private String slug;

    public Author() {
    }

    public Author(String nameLast, String nameFirst, String slug) {
       this.nameLast = nameLast;
       this.nameFirst = nameFirst;
       this.slug = slug;
    }
   
    public Integer getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(Integer idAuthor) {
        this.idAuthor = idAuthor;
    }
    public String getNameLast() {
        return this.nameLast;
    }
    
    public void setNameLast(String nameLast) {
        this.nameLast = nameLast;
    }
    public String getNameFirst() {
        return this.nameFirst;
    }
    
    public void setNameFirst(String nameFirst) {
        this.nameFirst = nameFirst;
    }
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }




}


