package criticfi_mydatos;
// Generated May 21, 2016 10:26:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer idItem;
     private Medium medium;
     private Integer idAuthor;
     private Date dateReleased;
     private String nameItem;
     private BigDecimal rating;
     private String synopsis;
     private String slug;

    public Item() {
    }

	
    public Item(Medium medium, Date dateReleased, String nameItem, BigDecimal rating, String slug) {
        this.medium = medium;
        this.dateReleased = dateReleased;
        this.nameItem = nameItem;
        this.rating = rating;
        this.slug = slug;
    }
    public Item(Medium medium, Integer idAuthor, Date dateReleased, String nameItem, BigDecimal rating, String synopsis, String slug) {
       this.medium = medium;
       this.idAuthor = idAuthor;
       this.dateReleased = dateReleased;
       this.nameItem = nameItem;
       this.rating = rating;
       this.synopsis = synopsis;
       this.slug = slug;
    }
   
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public Medium getMedium() {
        return this.medium;
    }
    
    public void setMedium(Medium medium) {
        this.medium = medium;
    }
    public Integer getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(Integer idAuthor) {
        this.idAuthor = idAuthor;
    }
    public Date getDateReleased() {
        return this.dateReleased;
    }
    
    public void setDateReleased(Date dateReleased) {
        this.dateReleased = dateReleased;
    }
    public String getNameItem() {
        return this.nameItem;
    }
    
    public void setNameItem(String nameItem) {
        this.nameItem = nameItem;
    }
    public BigDecimal getRating() {
        return this.rating;
    }
    
    public void setRating(BigDecimal rating) {
        this.rating = rating;
    }
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }




}


