package criticfi_mydatos;
// Generated May 21, 2016 10:26:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medium generated by hbm2java
 */
public class Medium  implements java.io.Serializable {


     private Integer idMedium;
     private String typeMedium;
     private Set genres = new HashSet(0);
     private Set items = new HashSet(0);

    public Medium() {
    }

    public Medium(String typeMedium, Set genres, Set items) {
       this.typeMedium = typeMedium;
       this.genres = genres;
       this.items = items;
    }
   
    public Integer getIdMedium() {
        return this.idMedium;
    }
    
    public void setIdMedium(Integer idMedium) {
        this.idMedium = idMedium;
    }
    public String getTypeMedium() {
        return this.typeMedium;
    }
    
    public void setTypeMedium(String typeMedium) {
        this.typeMedium = typeMedium;
    }
    public Set getGenres() {
        return this.genres;
    }
    
    public void setGenres(Set genres) {
        this.genres = genres;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


